### PR TITLE
Edits, mostly minor, throughout

### PR DESCRIPTION
**Pull request by moe52**

### CODE REVIEW

**Review by kimardenmiller — APPROVED** [review]
Looks good, Moe. Thanks for the edits.

**Comment by kimardenmiller** [comment]
Thanks for the edits, Moe. 

Point to remember: You now have the entire site on _your_ Github. That means that if I get _run over by a bus_, we’re not screwed. First, I'm not screwed because I'm  hang'n with virgins in heaven since I had to put up with you while on earth 😉.  Second, Momentum would want to now host the site from a different Github account anyway. To do that, one need only point the gomomentum.org DNS to, say, your Github account and you are done.

**Comment by kimardenmiller** [comment]
Check it out, Github now provides a full history of who has contributed to our site!
image

**Comment by kimardenmiller** [comment]
The changes go live immediately:
https://gomomentum.org/commitments/

**Comment by moe52** [comment]
I just made another change. Not sure how it goes live:

https://github.com/moe52/Momentum/blob/master/_posts/2017-09-30-commitments.markdown

Something else I need to do?

**Comment by kimardenmiller** [comment]
Just do another PR, though best practice is work in a branch, not your master. 

But may not matter this time. Try to just PR that.

Kim

**Comment by moe52** [comment]
I don’t see how to do a PR:

**Comment by kimardenmiller** [comment]
Step #4:
	https://discourse.gomomentum.org/t/editing-gomomentum-org-on-github/4008
Kim

**Comment by moe52** [comment]
I don’t see that:

**Comment by kimardenmiller** [comment]
Send me a screenshot of your https://github.com/moe52/Momentum 
Kim

**Comment by moe52** [comment]
Here it is again:

**Comment by kimardenmiller** [comment]
Nothing attached.

Maybe just go to Github and reply directly:
	https://github.com/kimardenmiller/Momentum/pull/2#issuecomment-417117887

**Comment by moe52** [comment]
Yeah, that's because Discourse (which is apparently what this uses) rudely just drops attachments when sent via email. Here it is. 
github screenshot 2018-08-29 19 26 31

**Comment by kimardenmiller** [comment]
Not Discourse ... just markdown-compatible, making it seem similar.

So ... there's the New Pull Request button in the middle of the screen, but you say _I don’t see how to do a PR_?

**Comment by moe52** [comment]
Different screen. I see it now, on the top level screen. 

Let’s see if we’re there…. Do you need to OK it for it to appear?

**Comment by kimardenmiller** [comment]
I automatically get an email to merge. Just the click of a button and we’re all set; changes are live. 
	https://github.com/kimardenmiller/Momentum/commits/master <https://github.com/kimardenmiller/Momentum/commits/master>

Kim

**Pull request merged**
